import { useEffect, useMemo, useState } from 'react';
import { AdminPanelSettingsOutlined as AdminIcon, DeleteOutlined as DeleteIcon, EditOutlined as EditIcon, GroupsOutlined as ClubsIcon, MenuBookOutlined as BooksIcon, PeopleAltOutlined as ReadersIcon, ReportOutlined as ReportsIcon, ShieldOutlined as ShieldIcon, UploadFileOutlined as UploadIcon } from '@mui/icons-material';
import { useAuth } from '../context/AuthContext.jsx';
import { useToast } from '../components/Toast.jsx';
import { ACHIEVEMENTS, READER_RANKS } from '../lib/achievements.js';
import { createBook, deleteAdminClub, deleteCatalogBook, getAdminClubs, getAdminReaders, getAdminReports, getBooks, getPlatformSettings, grantAdminAchievement, removeAdminAchievement, setAdminReaderRank, unpublishCatalogBook, updateAdminClub, updateAdminReport, updateAdminStreakSettings, updateCatalogBook, uploadReadingFile } from '../services/social.js';

const genres = ['Romance','Ficção Científica','Fantasia','Terror / Horror','Suspense / Thriller','Policial / Investigação','Ficção Histórica','Distopia','Realismo Mágico','Jovem Adulto (YA)','Biografia e Autobiografia','Memórias','História','Autoajuda e Desenvolvimento Pessoal','Negócios e Finanças','Filosofia e Sociologia','Divulgação Científica','Ensaios','Religião e Espiritualidade','True Crime'];
const blank = { title:'', author:'', cover_url:'', genre:'', description:'', page_count:'', visibility:'public' };
const tabs = [
  { id:'books', label:'Livros', icon:BooksIcon, permission:'books.view' },
  { id:'readers', label:'Leitores', icon:ReadersIcon, permission:'readers.view' },
  { id:'clubs', label:'Clubes', icon:ClubsIcon, permission:'clubs.view' },
  { id:'reports', label:'Denúncias', icon:ReportsIcon, permission:'reports.view' },
];

export default function Administracao() {
  const { user, profile } = useAuth();
  const toast = useToast();
  const permissions = profile?.admin_permissions || [];
  const has = (permission) => Boolean(profile?.is_owner || permissions.includes(permission));
  const availableTabs = useMemo(() => tabs.filter((tab) => has(tab.permission)), [profile?.is_owner, permissions.join('|')]);
  const [active, setActive] = useState('books');
  const [books, setBooks] = useState([]); const [readers, setReaders] = useState([]); const [clubs, setClubs] = useState([]); const [reports, setReports] = useState([]);
  const [form, setForm] = useState(blank); const [editingId, setEditingId] = useState(''); const [selectedBook, setSelectedBook] = useState(''); const [file, setFile] = useState(null); const [saving, setSaving] = useState(false); const [search, setSearch] = useState('');
  const [achievementChoice, setAchievementChoice] = useState({});
  const [streakSettings, setStreakSettings] = useState(null);

  const loadBooks = () => getBooks('', 0, 100).then(setBooks).catch((error) => toast(error.message));
  const loadReaders = () => getAdminReaders().then(setReaders).catch((error) => toast(error.message));
  const loadClubs = () => getAdminClubs().then(setClubs).catch((error) => toast(error.message));
  const loadReports = () => getAdminReports().then(setReports).catch((error) => toast(error.message));

  useEffect(() => {
    if (!profile?.is_admin && !profile?.is_owner) return;
    if (!availableTabs.some((tab) => tab.id === active)) setActive(availableTabs[0]?.id || '');
    if (has('books.view')) loadBooks();
    if (has('readers.view')) loadReaders();
    if (has('clubs.view')) loadClubs();
    if (has('reports.view')) loadReports();
    if (has('streak.manage')) getPlatformSettings().then(setStreakSettings).catch((error) => toast(error.message));
  }, [profile?.id, profile?.is_owner, permissions.join('|')]);

  if (!profile?.is_admin && !profile?.is_owner) return <section className="pagina ativa"><div className="admin-bloqueado widget"><AdminIcon /><h1>Área de administração</h1><p>Sua conta ainda não tem acesso administrativo.</p></div></section>;
  if (!availableTabs.length && !has('streak.manage')) return <section className="pagina ativa"><div className="admin-bloqueado widget"><AdminIcon /><h1>Permissões ainda não definidas</h1><p>O dono da plataforma precisa escolher quais áreas você pode administrar.</p></div></section>;

  function resetForm(){setForm(blank);setEditingId('');}
  async function saveBook(event) { event.preventDefault(); setSaving(true); try { const values={ ...form, title:form.title.trim(), author:form.author.trim(), genre:form.genre.trim() || null, description:form.description.trim() || null, cover_url:form.cover_url.trim() || null, page_count:Number(form.page_count) || null }; const book=editingId ? await updateCatalogBook(editingId,values) : await createBook(user.id,values); setBooks((current)=>editingId?current.map((item)=>item.id===book.id?book:item):[book,...current]);setSelectedBook(book.id);resetForm();toast(editingId?'Livro atualizado.':'Livro criado no catálogo.'); } catch(error){toast(error.message);} finally{setSaving(false);} }
  async function sendFile(event) { event.preventDefault(); if (!selectedBook || !file) return toast('Escolha o livro e o arquivo.'); setSaving(true); try { await uploadReadingFile(user.id, selectedBook, file); setFile(null); event.target.reset(); toast('Material de leitura enviado.'); } catch (error) { toast(error.message); } finally { setSaving(false); } }
  async function unpublish(book){try{await unpublishCatalogBook(book.id);setBooks((items)=>items.map((item)=>item.id===book.id?{...item,visibility:'private'}:item));toast('Livro removido da Explorar.');}catch(error){toast(error.message)}}
  async function removeBook(book){if(!window.confirm(`Excluir permanentemente “${book.title}”?`))return;try{await deleteCatalogBook(book.id);setBooks((items)=>items.filter((item)=>item.id!==book.id));toast('Livro excluído permanentemente.');}catch(error){toast(error.message)}}
  function editBook(book){setEditingId(book.id);setForm({title:book.title,author:book.author,cover_url:book.cover_url||'',genre:book.genre||'',description:book.description||'',page_count:book.page_count||'',visibility:book.visibility||'public'});window.scrollTo({top:0,behavior:'smooth'});}
  async function changeRank(reader, rank) { try { await setAdminReaderRank(reader.id, rank || null); setReaders((current) => current.map((item) => item.id === reader.id ? { ...item, reader_rank:rank || item.reader_rank, rank_manual:Boolean(rank) } : item)); toast(rank ? 'Rank manual aplicado.' : 'Progressão automática reativada.'); } catch (error) { toast(error.message); } }
  async function changeAchievement(reader, remove = false) { const id=achievementChoice[reader.id]; const achievement=ACHIEVEMENTS.find((item)=>item.id===id); if(!achievement)return toast('Escolha uma conquista.'); try { if(remove) await removeAdminAchievement(reader.id,id); else await grantAdminAchievement(reader.id,achievement); toast(remove?'Conquista manual removida.':'Conquista concedida.'); loadReaders(); } catch(error){toast(error.message);} }
  async function editClub(club) { const name=window.prompt('Nome do clube',club.name); if(name===null)return; const description=window.prompt('Descrição do clube',club.description||''); if(description===null)return; try{await updateAdminClub(club.id,{name,description,is_private:club.is_private});setClubs((current)=>current.map((item)=>item.id===club.id?{...item,name,description}:item));toast('Clube atualizado.');}catch(error){toast(error.message);} }
  async function toggleClubPrivacy(club) { try{await updateAdminClub(club.id,{...club,is_private:!club.is_private});setClubs((current)=>current.map((item)=>item.id===club.id?{...item,is_private:!item.is_private}:item));toast(club.is_private?'Clube tornado público.':'Clube tornado privado.');}catch(error){toast(error.message);} }
  async function removeClub(club) { if(!window.confirm(`Excluir permanentemente o clube “${club.name}”?`))return;try{await deleteAdminClub(club.id);setClubs((current)=>current.filter((item)=>item.id!==club.id));toast('Clube excluído.');}catch(error){toast(error.message);} }
  async function changeReport(report,status){try{await updateAdminReport(report.id,status);setReports((current)=>current.map((item)=>item.id===report.id?{...item,status}:item));toast('Denúncia atualizada.');}catch(error){toast(error.message)}}
  async function saveStreak(event){event.preventDefault();try{await updateAdminStreakSettings(streakSettings);toast('Configuração da ofensiva salva.');}catch(error){toast(error.message)}}

  const visibleBooks=books.filter((book)=>`${book.title} ${book.author} ${book.genre||''}`.toLowerCase().includes(search.toLowerCase().trim()));
  return <section className="pagina ativa admin-pagina">
    <div className="admin-hero"><span><AdminIcon /></span><div><p>EQUIPE DA PLATAFORMA</p><h1>Administração</h1><small>As áreas e ações abaixo respeitam as permissões atribuídas pelo dono.</small></div></div>
    <nav className="admin-tabs" aria-label="Áreas administrativas">{availableTabs.map(({id,label,icon:Icon})=><button key={id} className={active===id?'ativa':''} onClick={()=>setActive(id)}><Icon fontSize="small"/>{label}</button>)}</nav>

    {active==='books'&&has('books.view')&&<>
      {(has('books.create')||has('books.edit')||has('books.files'))&&<div className="admin-grid">
        {(has('books.create')||has('books.edit'))&&<form className="widget livro-form" onSubmit={saveBook}><h2>{editingId?'Editar livro':'Novo livro'}</h2><label>Título<input required value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></label><label>Autor<input required value={form.author} onChange={(e)=>setForm({...form,author:e.target.value})}/></label><label>Gênero<input list="catalogo-generos" value={form.genre} onChange={(e)=>setForm({...form,genre:e.target.value})} placeholder="Selecione ou escreva outro"/><datalist id="catalogo-generos">{genres.map((genre)=><option key={genre} value={genre}/>)}</datalist></label><label>Páginas<input type="number" min="1" value={form.page_count} onChange={(e)=>setForm({...form,page_count:e.target.value})}/></label><label className="livro-form__sinopse">Sinopse<textarea value={form.description} maxLength={3000} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><label>URL da capa<input type="url" value={form.cover_url} onChange={(e)=>setForm({...form,cover_url:e.target.value})}/></label><label>Visibilidade<select value={form.visibility} onChange={(e)=>setForm({...form,visibility:e.target.value})}><option value="public">Público na Explorar</option><option value="private">Não publicado</option></select></label><div className="admin-form__acoes"><button className="btn-primario" disabled={saving||(!editingId&&!has('books.create'))||(editingId&&!has('books.edit'))}>{editingId?'Salvar alterações':'Criar livro'}</button>{editingId&&<button type="button" className="btn-secundario" onClick={resetForm}>Cancelar</button>}</div></form>}
        {has('books.files')&&<form className="widget admin-arquivo" onSubmit={sendFile}><UploadIcon/><h2>Material de leitura</h2><p>PDF ou EPUB de até 20 MB. Envie apenas conteúdo próprio, licenciado ou de domínio público.</p><label>Livro<select required value={selectedBook} onChange={(e)=>setSelectedBook(e.target.value)}><option value="">Escolha um livro</option>{books.map((book)=><option key={book.id} value={book.id}>{book.title} — {book.author}</option>)}</select></label><label>Arquivo<input required type="file" accept="application/pdf,.pdf,application/epub+zip,.epub" onChange={(e)=>setFile(e.target.files?.[0]||null)}/></label><button className="btn-primario" disabled={saving}>Enviar material</button></form>}
      </div>}
      <section className="widget admin-catalogo"><header><div><h2>Gerenciar livros</h2><p>As ações disponíveis refletem sua permissão atual.</p></div><input type="search" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Buscar livro..."/></header><div>{visibleBooks.map((book)=><article key={book.id}>{book.cover_url?<img src={book.cover_url} alt=""/>:<span>{book.title.charAt(0)}</span>}<div><strong>{book.title}</strong><small>{book.author}{book.genre?` · ${book.genre}`:''}</small><em>{book.visibility==='private'?'Não publicado':'Público'}</em></div><nav>{has('books.edit')&&<button type="button" onClick={()=>editBook(book)}><EditIcon fontSize="small"/>Editar</button>}{has('books.unpublish')&&book.visibility!=='private'&&<button type="button" onClick={()=>unpublish(book)}>Despublicar</button>}{has('books.delete')&&<button type="button" className="perigo" onClick={()=>removeBook(book)}><DeleteIcon fontSize="small"/></button>}</nav></article>)}</div></section>
    </>}

    {active==='readers'&&has('readers.view')&&<section className="widget admin-lista"><header><div><h2>Leitores</h2><p>Consulte a atividade, ajuste ranks e gerencie conquistas manuais.</p></div></header>{readers.map((reader)=><article key={reader.id}><span className="owner-usuarios__avatar">{reader.avatar_url?<img src={reader.avatar_url} alt=""/>:reader.display_name?.[0]}</span><div><strong>{reader.display_name}</strong><small>@{reader.username} · {reader.books_count} livros · {reader.achievements_count} conquistas</small></div>{has('ranks.manage')&&<label>Rank<select value={reader.rank_manual?reader.reader_rank:''} onChange={(e)=>changeRank(reader,e.target.value)}><option value="">Automático</option>{READER_RANKS.map((rank)=><option key={rank.key} value={rank.key}>{rank.label}</option>)}</select></label>}{(has('achievements.grant')||has('achievements.remove'))&&<div className="admin-conquista"><select value={achievementChoice[reader.id]||''} onChange={(e)=>setAchievementChoice({...achievementChoice,[reader.id]:e.target.value})}><option value="">Escolha uma conquista</option>{ACHIEVEMENTS.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select>{has('achievements.grant')&&<button className="btn-secundario" onClick={()=>changeAchievement(reader)}>Conceder</button>}{has('achievements.remove')&&<button className="btn-texto-perigo" onClick={()=>changeAchievement(reader,true)}>Remover manual</button>}</div>}</article>)}</section>}

    {active==='clubs'&&has('clubs.view')&&<section className="widget admin-lista"><header><div><h2>Clubes</h2><p>Visualize e modere os espaços da comunidade.</p></div></header>{clubs.map((club)=><article key={club.id}><ClubsIcon/><div><strong>{club.name}</strong><small>{club.member_count} membros · por {club.owner_name} · {club.is_private?'privado':'público'}</small><p>{club.description}</p></div><nav>{has('clubs.edit')&&<><button className="btn-secundario" onClick={()=>editClub(club)}><EditIcon fontSize="small"/>Editar</button><button className="btn-secundario" onClick={()=>toggleClubPrivacy(club)}>{club.is_private?'Tornar público':'Tornar privado'}</button></>}{has('clubs.delete')&&<button className="btn-texto-perigo" onClick={()=>removeClub(club)}>Excluir</button>}</nav></article>)}</section>}

    {active==='reports'&&has('reports.view')&&<section className="widget admin-lista"><header><div><h2>Denúncias</h2><p>Analise o conteúdo denunciado e registre a decisão.</p></div></header>{reports.map((report)=><article key={report.id}><ReportsIcon/><div><strong>{report.reason} · {report.target_type}</strong><small>Enviada por {report.reporter_name} · {new Date(report.created_at).toLocaleDateString('pt-BR')}</small><p>{report.target_summary}{report.details?` — ${report.details}`:''}</p></div><label>Status<select value={report.status} disabled={!has('reports.resolve')&&!has('reports.archive')} onChange={(e)=>changeReport(report,e.target.value)}><option value="open" disabled={!has('reports.resolve')}>Aberta</option><option value="reviewing" disabled={!has('reports.resolve')}>Em análise</option><option value="resolved" disabled={!has('reports.resolve')}>Resolvida</option><option value="dismissed" disabled={!has('reports.archive')}>Arquivada</option></select></label></article>)}</section>}

    {has('streak.manage')&&streakSettings&&<form className="widget admin-streak" onSubmit={saveStreak}><header><ShieldIcon/><div><h2>Proteção da ofensiva</h2><p>As proteções são aplicadas automaticamente quando um dia de leitura é perdido.</p></div></header><label>Dias exibidos<input type="number" min="7" max="366" value={streakSettings.streak_days_displayed} onChange={(e)=>setStreakSettings({...streakSettings,streak_days_displayed:Number(e.target.value)})}/></label><label>Proteções por mês<input type="number" min="0" max="31" value={streakSettings.streak_max_protections} onChange={(e)=>setStreakSettings({...streakSettings,streak_max_protections:Number(e.target.value)})}/></label><button className="btn-primario">Salvar configuração</button></form>}
  </section>;
}
