import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { getDocument, GlobalWorkerOptions } from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import { AutoStoriesOutlined as ReaderIcon, BookmarkAddOutlined as BookmarkIcon, ChevronLeft, ChevronRight, FormatSizeOutlined as FontIcon, GridViewOutlined as GridIcon, LockOutlined as LockIcon, PaletteOutlined as PaletteIcon, SettingsOutlined as SettingsIcon, StickyNote2Outlined as NoteIcon } from '@mui/icons-material';
import { useAuth } from '../context/AuthContext.jsx';
import { getReadingFileUrl, saveAutomaticReadingProgress, saveReadingNote } from '../services/social.js';
import { useToast } from './Toast.jsx';
import PdfPageCanvas from './PdfPageCanvas.jsx';

GlobalWorkerOptions.workerSrc = workerUrl;
const themes = [{ id:'day', label:'Dia' }, { id:'night', label:'Noite' }, { id:'contrast', label:'Noite contrastada' }, { id:'sepia', label:'Sépia' }, { id:'sepiaContrast', label:'Sépia contrastada' }, { id:'custom', label:'Personalizado' }];
const markerColors = ['yellow', 'green', 'blue', 'purple', 'red', 'orange'];

export default function ReadingExperience({ bookId, bookTitle, files, pageFromNotebook, onAnnotationSaved, onProgressChange }) {
  const { user } = useAuth(); const toast = useToast(); const storageKey = `reader-settings:${bookId}`;
  const [settings, setSettings] = useState(() => { try { return { theme:'day', direction:'horizontal', fontSize:18, margin:42, marginLocked:false, page:1, customBackground:'#f8fafc', customText:'#1e1b4b', ...JSON.parse(localStorage.getItem(storageKey) || '{}') }; } catch { return { theme:'day', direction:'horizontal', fontSize:18, margin:42, marginLocked:false, page:1, customBackground:'#f8fafc', customText:'#1e1b4b' }; } });
  const [activeFileId, setActiveFileId] = useState(''); const [activeUrl, setActiveUrl] = useState(''); const [pdf, setPdf] = useState(null); const [totalPages, setTotalPages] = useState(0); const [loadingPdf, setLoadingPdf] = useState(false); const [showPages, setShowPages] = useState(false); const [showNote, setShowNote] = useState(false); const [note, setNote] = useState({ quote:'', content:'', color:'yellow' }); const saveTimer = useRef(null);
  const activeFile = useMemo(() => files.find((file) => file.id === activeFileId) || files[0], [files, activeFileId]);
  const page = Math.max(1, Math.min(totalPages || 1, Number(settings.page) || 1)); const progress = totalPages ? Math.round((page / totalPages) * 100) : 0; const scale = Math.max(.85, Math.min(1.8, settings.fontSize / 15));

  useEffect(() => { localStorage.setItem(storageKey, JSON.stringify(settings)); }, [settings, storageKey]);
  useEffect(() => { if (pageFromNotebook) setSettings((current) => ({ ...current, page:Number(pageFromNotebook) })); }, [pageFromNotebook]);
  useEffect(() => { if (!activeFile) { setActiveUrl(''); return; } getReadingFileUrl(activeFile.file_path).then(setActiveUrl).catch((error) => toast(error.message)); }, [activeFile?.id, toast]);
  useEffect(() => { if (!activeUrl || activeFile?.file_type !== 'pdf') { setPdf(null); setTotalPages(0); return undefined; } let cancelled = false; setLoadingPdf(true); setPdf(null); setTotalPages(0); const task = getDocument(activeUrl); task.promise.then((document) => { if (!cancelled) { setPdf(document); setTotalPages(document.numPages); } }).catch(() => { if (!cancelled) toast('Não foi possível carregar este PDF no leitor.'); }).finally(() => { if (!cancelled) setLoadingPdf(false); }); return () => { cancelled = true; task.destroy(); }; }, [activeUrl, activeFile?.file_type, toast]);
  useEffect(() => { if (!totalPages || !user?.id) return undefined; clearTimeout(saveTimer.current); saveTimer.current = setTimeout(() => { saveAutomaticReadingProgress(user.id, bookId, progress).then(() => onProgressChange?.(progress)).catch(() => {}); }, 800); return () => clearTimeout(saveTimer.current); }, [bookId, page, progress, totalPages, user?.id, onProgressChange]);
  useEffect(() => () => clearTimeout(saveTimer.current), []);
  useEffect(() => { if (settings.direction !== 'horizontal') return undefined; const keydown = (event) => { if (event.target.matches('input, textarea, select')) return; if (event.key === 'ArrowLeft') setSettings((value) => ({ ...value, page:Math.max(1, Number(value.page) - 1) })); if (event.key === 'ArrowRight') setSettings((value) => ({ ...value, page:Math.min(totalPages || 1, Number(value.page) + 1) })); }; window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown); }, [settings.direction, totalPages]);

  const update = useCallback((key, value) => setSettings((current) => ({ ...current, [key]:value })), []);
  const goToPage = (nextPage) => update('page', Math.max(1, Math.min(totalPages || 1, Number(nextPage) || 1)));
  const nearbyPages = settings.direction === 'vertical' ? [page - 1, page, page + 1].filter((item) => item >= 1 && item <= totalPages) : [page];
  async function saveAnnotation(event) { event.preventDefault(); const content = [note.quote.trim() && `“${note.quote.trim()}”`, note.content.trim()].filter(Boolean).join('\n'); if (!content) return toast('Escreva um trecho ou uma anotação.'); try { await saveReadingNote(user.id, bookId, { kind:note.quote.trim() ? 'citation' : 'reflection', content, progress, pageNumber:page, color:note.color }); setNote({ quote:'', content:'', color:'yellow' }); setShowNote(false); onAnnotationSaved?.(); toast('Guardado no seu caderno privado.'); } catch (error) { toast(error.message); } }
  async function favoritePage() { try { await saveReadingNote(user.id, bookId, { kind:'favorite', content:`Página favorita de ${bookTitle || 'este livro'}.`, progress, pageNumber:page, color:'yellow' }); onAnnotationSaved?.(); toast(`Página ${page} adicionada aos favoritos.`); } catch (error) { toast(error.message); } }
  const style = settings.theme === 'custom' ? { '--reader-background':settings.customBackground, '--reader-text':settings.customText, '--reader-margin':`${settings.margin}px` } : { '--reader-margin':`${settings.margin}px` };

  return <section className={`experiencia-leitura experiencia-leitura--${settings.theme} experiencia-leitura--${settings.direction} widget`} style={style}>
    <header><span><ReaderIcon /></span><div><h2>Experiência de leitura</h2><p>Leia dentro do Entre Leitores. Sua página e preferências são salvas automaticamente.</p></div></header>
    <div className="experiencia-leitura__controles"><label><PaletteIcon fontSize="small" />Tema<select value={settings.theme} onChange={(e) => update('theme', e.target.value)}>{themes.map((theme) => <option key={theme.id} value={theme.id}>{theme.label}</option>)}</select></label><label>Modo<select value={settings.direction} onChange={(e) => update('direction', e.target.value)}><option value="vertical">Rolagem vertical</option><option value="horizontal">Página a página</option></select></label><label><FontIcon fontSize="small" />Visualização<input aria-label="Tamanho da visualização" type="range" min="14" max="27" value={settings.fontSize} onChange={(e) => update('fontSize', Number(e.target.value))} /></label><label>Margens<input aria-label="Margens" type="range" min="0" max="80" value={settings.margin} disabled={settings.marginLocked} onChange={(e) => update('margin', Number(e.target.value))} /></label><button type="button" className={`experiencia-leitura__lock${settings.marginLocked ? ' ativa' : ''}`} onClick={() => update('marginLocked', !settings.marginLocked)}><LockIcon fontSize="small" />{settings.marginLocked ? 'Margens fixas' : 'Fixar margens'}</button><button type="button" className="experiencia-leitura__icon" title="Abrir anotações" onClick={() => setShowNote((value) => !value)}><NoteIcon fontSize="small" /></button><button type="button" className="experiencia-leitura__icon" title="Favoritar esta página" onClick={favoritePage}><BookmarkIcon fontSize="small" /></button></div>
    {settings.theme === 'custom' && <div className="experiencia-leitura__cores"><label>Fundo<input type="color" value={settings.customBackground} onChange={(e) => update('customBackground', e.target.value)} /></label><label>Texto<input type="color" value={settings.customText} onChange={(e) => update('customText', e.target.value)} /></label></div>}
    {showNote && <form className="experiencia-leitura__anotacao" onSubmit={saveAnnotation}><strong>Nova marcação na página {page}</strong><input value={note.quote} maxLength={1200} onChange={(e) => setNote({ ...note, quote:e.target.value })} placeholder="Trecho ou citação (opcional)" /><textarea value={note.content} maxLength={1800} onChange={(e) => setNote({ ...note, content:e.target.value })} placeholder="Sua anotação" /><label>Cor<select value={note.color} onChange={(e) => setNote({ ...note, color:e.target.value })}>{markerColors.map((color) => <option key={color} value={color}>{({yellow:'Amarelo',green:'Verde',blue:'Azul',purple:'Roxo',red:'Vermelho',orange:'Laranja'})[color]}</option>)}</select></label><button className="btn-primario">Guardar no caderno</button></form>}
    <div className="experiencia-leitura__arquivo"><label>Material<select value={activeFile?.id || ''} onChange={(e) => setActiveFileId(e.target.value)}><option value="">{files.length ? 'Escolha um material' : 'Nenhum material enviado'}</option>{files.map((file) => <option key={file.id} value={file.id}>{file.file_name}</option>)}</select></label></div>
    {activeFile?.file_type === 'pdf' && activeUrl ? <><div className="experiencia-leitura__pagina"><button type="button" className="experiencia-leitura__nav" disabled={page <= 1} onClick={() => goToPage(page - 1)}><ChevronLeft />Anterior</button><label>Ir para página<input type="number" min="1" max={totalPages || undefined} value={page} onChange={(e) => goToPage(e.target.value)} /></label><strong>{totalPages ? `Página ${page} de ${totalPages}` : 'Carregando páginas...'}</strong><button type="button" className="experiencia-leitura__nav" disabled={!totalPages || page >= totalPages} onClick={() => goToPage(page + 1)}>Próxima<ChevronRight /></button><button type="button" className="experiencia-leitura__grid-btn" onClick={() => setShowPages((value) => !value)}><GridIcon fontSize="small" />Todas as páginas</button></div><div className="experiencia-leitura__progresso"><span style={{ width:`${progress}%` }} /><small>{progress}% lido</small></div>{showPages && <div className="experiencia-leitura__miniaturas" aria-label="Todas as páginas">{Array.from({ length:totalPages }, (_, index) => <button type="button" className={page === index + 1 ? 'ativa' : ''} key={index} onClick={() => { goToPage(index + 1); setShowPages(false); }}><span>{index + 1}</span></button>)}</div>}<div className="experiencia-leitura__pdf" aria-busy={loadingPdf}>{loadingPdf ? <div className="experiencia-leitura__aviso">Carregando o PDF…</div> : nearbyPages.map((item) => <div className="experiencia-leitura__folha" key={item}><PdfPageCanvas document={pdf} page={item} scale={scale} /><small>Página {item}</small></div>)}</div></> : activeFile ? <div className="experiencia-leitura__aviso">Este material usa um formato compatível com outro aplicativo. Envie um PDF para ler aqui no Entre Leitores.</div> : <div className="experiencia-leitura__aviso">Quando houver material autorizado para este livro, ele aparecerá aqui.</div>}
    <footer><SettingsIcon fontSize="small" /> Preferências salvas automaticamente para este livro.</footer>
  </section>;
}
