-- Expansão do leitor, conquistas persistentes, ranks, permissões granulares e ofensiva automática.

alter table public.profiles add column if not exists admin_permissions text[] not null default '{}';
alter table public.profiles add column if not exists reader_rank text not null default 'visitor'
  check (reader_rank in ('visitor','explorer','debater','connector','curator','legend'));
alter table public.profiles add column if not exists rank_manual boolean not null default false;

create or replace function public.prevent_self_admin_change()
returns trigger language plpgsql set search_path = public as $$
begin
  if auth.uid() is not null
    and current_setting('app.allow_role_change', true) is distinct from 'true'
    and (
      new.is_admin is distinct from old.is_admin
      or new.is_owner is distinct from old.is_owner
      or new.admin_permissions is distinct from old.admin_permissions
      or new.reader_rank is distinct from old.reader_rank
      or new.rank_manual is distinct from old.rank_manual
    ) then
    raise exception 'role, permission and rank changes require authorized functions';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_prevent_self_admin_change on public.profiles;
create trigger profiles_prevent_self_admin_change
before update of is_admin, is_owner, admin_permissions, reader_rank, rank_manual on public.profiles
for each row execute function public.prevent_self_admin_change();

create or replace function public.has_admin_permission(required_permission text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and (is_owner = true or (is_admin = true and required_permission = any(admin_permissions)))
  );
$$;
revoke all on function public.has_admin_permission(text) from public, anon;
grant execute on function public.has_admin_permission(text) to authenticated;

-- Preserva o acesso editorial de administradores que já existiam antes das permissões granulares.
update public.profiles
set admin_permissions = array['books.view','books.create','books.edit','books.unpublish','books.files']::text[]
where is_admin = true and is_owner = false and cardinality(admin_permissions) = 0;

create table if not exists public.platform_settings (
  singleton boolean primary key default true check (singleton),
  streak_days_displayed integer not null default 30 check (streak_days_displayed between 7 and 366),
  streak_max_protections integer not null default 5 check (streak_max_protections between 0 and 31),
  streak_renewal text not null default 'monthly' check (streak_renewal in ('monthly')),
  rank_thresholds jsonb not null default '{"explorer":100,"debater":500,"connector":1500,"curator":5000,"legend":10000}'::jsonb,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.platform_settings(singleton) values(true) on conflict(singleton) do nothing;
alter table public.platform_settings enable row level security;
drop policy if exists "authenticated users read platform settings" on public.platform_settings;
create policy "authenticated users read platform settings" on public.platform_settings
  for select to authenticated using (true);

create table if not exists public.user_achievements (
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_id text not null check (char_length(achievement_id) between 2 and 100),
  xp integer not null default 0 check (xp >= 0),
  unlock_type text not null default 'automatic' check (unlock_type in ('automatic','manual')),
  granted_by uuid references public.profiles(id) on delete set null,
  unlocked_at timestamptz not null default now(),
  primary key(user_id, achievement_id)
);
create index if not exists user_achievements_unlocked_idx on public.user_achievements(user_id, unlocked_at desc);
alter table public.user_achievements enable row level security;
drop policy if exists "users read own achievements" on public.user_achievements;
drop policy if exists "authorized admins read achievements" on public.user_achievements;
create policy "users read own achievements" on public.user_achievements for select
  using (auth.uid() = user_id);
create policy "authorized admins read achievements" on public.user_achievements for select
  using (public.has_admin_permission('readers.view') or public.has_admin_permission('achievements.grant'));

create table if not exists public.reader_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  book_id uuid references public.books(id) on delete cascade,
  event_type text not null check (event_type in ('theme','font','margin','page_jump','page_overview','resume')),
  value text,
  occurred_at timestamptz not null default now()
);
create index if not exists reader_events_user_type_idx on public.reader_events(user_id, event_type, occurred_at desc);
alter table public.reader_events enable row level security;
drop policy if exists "users read own reader events" on public.reader_events;
drop policy if exists "users create own reader events" on public.reader_events;
create policy "users read own reader events" on public.reader_events for select using (auth.uid() = user_id);
create policy "users create own reader events" on public.reader_events for insert with check (auth.uid() = user_id);

create or replace function public.owner_set_admin_permissions(target_user_id uuid, grant_admin boolean, granted_permissions text[] default '{}')
returns void language plpgsql security definer set search_path = public as $$
declare allowed_permissions constant text[] := array[
  'books.view','books.create','books.edit','books.unpublish','books.delete','books.files',
  'readers.view','ranks.manage','achievements.grant','achievements.remove',
  'clubs.view','clubs.edit','clubs.delete',
  'reports.view','reports.resolve','reports.archive','streak.manage'
];
begin
  if not public.is_app_owner() then raise exception 'Owner access required'; end if;
  if not exists (select 1 from public.profiles where id = target_user_id) then raise exception 'User not found'; end if;
  if exists (select 1 from public.profiles where id = target_user_id and is_owner) then raise exception 'Owner roles cannot be changed here'; end if;
  if exists (select 1 from unnest(coalesce(granted_permissions, '{}')) permission where not permission = any(allowed_permissions)) then
    raise exception 'Invalid administrator permission';
  end if;
  perform set_config('app.allow_role_change', 'true', true);
  update public.profiles
  set is_admin = grant_admin,
      admin_permissions = case when grant_admin then coalesce(granted_permissions, '{}') else '{}' end
  where id = target_user_id;
end;
$$;
revoke all on function public.owner_set_admin_permissions(uuid, boolean, text[]) from public, anon;
grant execute on function public.owner_set_admin_permissions(uuid, boolean, text[]) to authenticated;

create or replace function public.owner_set_admin(target_user_id uuid, grant_admin boolean)
returns void language plpgsql security definer set search_path = public as $$
begin
  perform public.owner_set_admin_permissions(
    target_user_id,
    grant_admin,
    case when grant_admin then array['books.view','books.create','books.edit','books.unpublish','books.files']::text[] else '{}'::text[] end
  );
end;
$$;

create or replace function public.sync_user_achievements(achievement_ids text[], achievement_xp integer[])
returns integer language plpgsql security definer set search_path = public as $$
declare inserted_count integer := 0;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if cardinality(coalesce(achievement_ids, '{}')) <> cardinality(coalesce(achievement_xp, '{}')) then
    raise exception 'Achievement arrays must have the same length';
  end if;
  if cardinality(coalesce(achievement_ids, '{}')) > 0 then
    for item_index in 1..cardinality(achievement_ids) loop
      insert into public.user_achievements(user_id, achievement_id, xp, unlock_type)
      values(auth.uid(), achievement_ids[item_index], greatest(0, achievement_xp[item_index]), 'automatic')
      on conflict(user_id, achievement_id) do nothing;
      if found then inserted_count := inserted_count + 1; end if;
    end loop;
  end if;
  return inserted_count;
end;
$$;
revoke all on function public.sync_user_achievements(text[], integer[]) from public, anon;
grant execute on function public.sync_user_achievements(text[], integer[]) to authenticated;

create or replace function public.admin_grant_achievement(target_user_id uuid, target_achievement_id text, target_xp integer)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.has_admin_permission('achievements.grant') then raise exception 'Achievement grant permission required'; end if;
  insert into public.user_achievements(user_id, achievement_id, xp, unlock_type, granted_by)
  values(target_user_id, target_achievement_id, greatest(0, target_xp), 'manual', auth.uid())
  on conflict(user_id, achievement_id) do nothing;
end;
$$;
revoke all on function public.admin_grant_achievement(uuid, text, integer) from public, anon;
grant execute on function public.admin_grant_achievement(uuid, text, integer) to authenticated;

create or replace function public.admin_remove_manual_achievement(target_user_id uuid, target_achievement_id text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.has_admin_permission('achievements.remove') then raise exception 'Achievement removal permission required'; end if;
  delete from public.user_achievements
  where user_id = target_user_id and achievement_id = target_achievement_id and unlock_type = 'manual';
end;
$$;
revoke all on function public.admin_remove_manual_achievement(uuid, text) from public, anon;
grant execute on function public.admin_remove_manual_achievement(uuid, text) to authenticated;

create or replace function public.admin_set_reader_rank(target_user_id uuid, target_rank text default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.has_admin_permission('ranks.manage') then raise exception 'Rank permission required'; end if;
  if target_rank is not null and target_rank not in ('visitor','explorer','debater','connector','curator','legend') then
    raise exception 'Invalid reader rank';
  end if;
  perform set_config('app.allow_role_change', 'true', true);
  update public.profiles
  set reader_rank = coalesce(target_rank, reader_rank), rank_manual = target_rank is not null
  where id = target_user_id;
end;
$$;
revoke all on function public.admin_set_reader_rank(uuid, text) from public, anon;
grant execute on function public.admin_set_reader_rank(uuid, text) to authenticated;

create or replace function public.sync_reader_rank()
returns text language plpgsql security definer set search_path = public as $$
declare thresholds jsonb; next_rank text := 'visitor'; earned_xp integer := 0;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select coalesce(sum(xp), 0) into earned_xp from public.user_achievements where user_id = auth.uid();
  select rank_thresholds into thresholds from public.platform_settings where singleton = true;
  if earned_xp >= coalesce((thresholds->>'explorer')::integer, 100) then next_rank := 'explorer'; end if;
  if earned_xp >= coalesce((thresholds->>'debater')::integer, 500) then next_rank := 'debater'; end if;
  if earned_xp >= coalesce((thresholds->>'connector')::integer, 1500) then next_rank := 'connector'; end if;
  if earned_xp >= coalesce((thresholds->>'curator')::integer, 5000) then next_rank := 'curator'; end if;
  if earned_xp >= coalesce((thresholds->>'legend')::integer, 10000) then next_rank := 'legend'; end if;
  perform set_config('app.allow_role_change', 'true', true);
  update public.profiles set reader_rank = next_rank where id = auth.uid() and rank_manual = false;
  return (select reader_rank from public.profiles where id = auth.uid());
end;
$$;
revoke all on function public.sync_reader_rank() from public, anon;
grant execute on function public.sync_reader_rank() to authenticated;

create or replace function public.owner_update_platform_settings(
  displayed_days integer,
  max_protections integer,
  renewal_period text,
  new_rank_thresholds jsonb
)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_app_owner() then raise exception 'Owner access required'; end if;
  if displayed_days not between 7 and 366 or max_protections not between 0 and 31 or renewal_period <> 'monthly' then
    raise exception 'Invalid platform settings';
  end if;
  if (new_rank_thresholds->>'explorer')::integer < 0
    or (new_rank_thresholds->>'debater')::integer <= (new_rank_thresholds->>'explorer')::integer
    or (new_rank_thresholds->>'connector')::integer <= (new_rank_thresholds->>'debater')::integer
    or (new_rank_thresholds->>'curator')::integer <= (new_rank_thresholds->>'connector')::integer
    or (new_rank_thresholds->>'legend')::integer <= (new_rank_thresholds->>'curator')::integer then
    raise exception 'Rank thresholds must be increasing';
  end if;
  update public.platform_settings set
    streak_days_displayed = displayed_days,
    streak_max_protections = max_protections,
    streak_renewal = renewal_period,
    rank_thresholds = new_rank_thresholds,
    updated_by = auth.uid(), updated_at = now()
  where singleton = true;
end;
$$;
revoke all on function public.owner_update_platform_settings(integer, integer, text, jsonb) from public, anon;
grant execute on function public.owner_update_platform_settings(integer, integer, text, jsonb) to authenticated;

create or replace function public.admin_update_streak_settings(displayed_days integer, max_protections integer, renewal_period text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.has_admin_permission('streak.manage') then raise exception 'Streak settings permission required'; end if;
  if displayed_days not between 7 and 366 or max_protections not between 0 and 31 or renewal_period <> 'monthly' then
    raise exception 'Invalid streak settings';
  end if;
  update public.platform_settings set streak_days_displayed = displayed_days,
    streak_max_protections = max_protections, streak_renewal = renewal_period,
    updated_by = auth.uid(), updated_at = now()
  where singleton = true;
end;
$$;
revoke all on function public.admin_update_streak_settings(integer, integer, text) from public, anon;
grant execute on function public.admin_update_streak_settings(integer, integer, text) to authenticated;

drop policy if exists "public books and private owner access" on public.books;
drop policy if exists "readers add private books and admins add public books" on public.books;
drop policy if exists "owners update private books and admins manage catalog" on public.books;
drop policy if exists "owners delete private books and admins delete catalog" on public.books;
create policy "public private owner and catalog viewers read books" on public.books for select to authenticated
  using (visibility = 'public' or created_by = auth.uid() or public.has_admin_permission('books.view'));
create policy "readers add private books and catalog creators add public books" on public.books for insert to authenticated
  with check (auth.uid() = created_by and (visibility = 'private' or public.has_admin_permission('books.create')));
create policy "owners edit private books and catalog editors manage books" on public.books for update to authenticated
  using ((created_by = auth.uid() and visibility = 'private') or public.has_admin_permission('books.edit'))
  with check ((created_by = auth.uid() and visibility = 'private') or public.has_admin_permission('books.edit'));
create policy "owners delete private books and catalog deleters remove books" on public.books for delete to authenticated
  using ((created_by = auth.uid() and visibility = 'private') or public.has_admin_permission('books.delete'));

create or replace function public.admin_unpublish_book(target_book_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.has_admin_permission('books.unpublish') then raise exception 'Unpublish permission required'; end if;
  update public.books set visibility = 'private' where id = target_book_id;
end;
$$;
revoke all on function public.admin_unpublish_book(uuid) from public, anon;
grant execute on function public.admin_unpublish_book(uuid) to authenticated;

drop policy if exists "readers see public files and their private files" on public.book_reading_files;
drop policy if exists "owners manage private files and admins manage catalog files" on public.book_reading_files;
create policy "readers see public files and their private files" on public.book_reading_files for select to authenticated
  using (public.has_admin_permission('books.view') or exists (
    select 1 from public.books where books.id = book_reading_files.book_id
      and (books.visibility = 'public' or books.created_by = auth.uid())
  ));
create policy "owners manage private files and authorized admins manage catalog files" on public.book_reading_files for all to authenticated
  using (public.has_admin_permission('books.files') or exists (
    select 1 from public.books where books.id = book_reading_files.book_id
      and books.visibility = 'private' and books.created_by = auth.uid()
  ))
  with check (public.has_admin_permission('books.files') or exists (
    select 1 from public.books where books.id = book_reading_files.book_id
      and books.visibility = 'private' and books.created_by = auth.uid()
  ));

drop policy if exists "owners upload private reading materials" on storage.objects;
drop policy if exists "owners update private reading materials" on storage.objects;
drop policy if exists "owners remove private reading materials" on storage.objects;
create policy "owners and authorized admins upload reading materials" on storage.objects for insert to authenticated
  with check (bucket_id = 'reading-materials' and (public.has_admin_permission('books.files') or split_part(name, '/', 1) = auth.uid()::text));
create policy "owners and authorized admins update reading materials" on storage.objects for update to authenticated
  using (bucket_id = 'reading-materials' and (public.has_admin_permission('books.files') or split_part(name, '/', 1) = auth.uid()::text))
  with check (bucket_id = 'reading-materials' and (public.has_admin_permission('books.files') or split_part(name, '/', 1) = auth.uid()::text));
create policy "owners and authorized admins remove reading materials" on storage.objects for delete to authenticated
  using (bucket_id = 'reading-materials' and (public.has_admin_permission('books.files') or split_part(name, '/', 1) = auth.uid()::text));

create or replace function public.admin_list_readers()
returns table(
  id uuid, display_name text, username text, avatar_url text, reader_rank text, rank_manual boolean,
  books_count bigint, achievements_count bigint
) language plpgsql stable security definer set search_path = public as $$
begin
  if not public.has_admin_permission('readers.view') then raise exception 'Reader view permission required'; end if;
  return query select p.id, p.display_name, p.username, p.avatar_url, p.reader_rank, p.rank_manual,
    (select count(*) from public.user_books ub where ub.user_id = p.id),
    (select count(*) from public.user_achievements ua where ua.user_id = p.id)
  from public.profiles p order by p.created_at desc limit 500;
end;
$$;
revoke all on function public.admin_list_readers() from public, anon;
grant execute on function public.admin_list_readers() to authenticated;

create or replace function public.admin_list_clubs()
returns table(id uuid, name text, description text, is_private boolean, created_at timestamptz, owner_id uuid, owner_name text, member_count bigint)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.has_admin_permission('clubs.view') then raise exception 'Club view permission required'; end if;
  return query select c.id, c.name, c.description, c.is_private, c.created_at, c.owner_id, p.display_name,
    (select count(*) from public.club_members cm where cm.club_id = c.id)
  from public.clubs c join public.profiles p on p.id = c.owner_id order by c.created_at desc;
end;
$$;
revoke all on function public.admin_list_clubs() from public, anon;
grant execute on function public.admin_list_clubs() to authenticated;

create or replace function public.admin_update_club(target_club_id uuid, new_name text, new_description text, new_is_private boolean)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.has_admin_permission('clubs.edit') then raise exception 'Club edit permission required'; end if;
  update public.clubs set name = btrim(new_name), description = nullif(btrim(new_description), ''), is_private = new_is_private
  where id = target_club_id;
end;
$$;
revoke all on function public.admin_update_club(uuid, text, text, boolean) from public, anon;
grant execute on function public.admin_update_club(uuid, text, text, boolean) to authenticated;

create or replace function public.admin_delete_club(target_club_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.has_admin_permission('clubs.delete') then raise exception 'Club deletion permission required'; end if;
  delete from public.clubs where id = target_club_id;
end;
$$;
revoke all on function public.admin_delete_club(uuid) from public, anon;
grant execute on function public.admin_delete_club(uuid) to authenticated;

create or replace function public.admin_list_reports()
returns table(id uuid, target_type text, target_id uuid, reason text, details text, status text, created_at timestamptz, reporter_name text, target_summary text)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.has_admin_permission('reports.view') then raise exception 'Report view permission required'; end if;
  return query select r.id, r.target_type, r.target_id, r.reason, r.details, r.status, r.created_at, p.display_name,
    case r.target_type
      when 'profile' then coalesce((select 'Perfil: ' || target_profile.display_name || ' (@' || target_profile.username || ')' from public.profiles target_profile where target_profile.id = r.target_id), 'Perfil removido')
      when 'post' then coalesce((select left(target_post.content, 240) from public.posts target_post where target_post.id = r.target_id), 'Publicação removida')
      when 'comment' then coalesce((select left(target_comment.content, 240) from public.comments target_comment where target_comment.id = r.target_id), 'Comentário removido')
      when 'message' then coalesce((select left(target_message.content, 240) from public.community_messages target_message where target_message.id = r.target_id), 'Mensagem removida')
      when 'book' then coalesce((select 'Livro: ' || target_book.title from public.books target_book where target_book.id = r.target_id), 'Livro removido')
      else 'Conteúdo não identificado'
    end
  from public.reports r join public.profiles p on p.id = r.reporter_id order by r.created_at desc;
end;
$$;
revoke all on function public.admin_list_reports() from public, anon;
grant execute on function public.admin_list_reports() to authenticated;

create or replace function public.admin_update_report(target_report_id uuid, new_status text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if new_status not in ('open','reviewing','resolved','dismissed') then raise exception 'Invalid report status'; end if;
  if new_status = 'dismissed' and not public.has_admin_permission('reports.archive') then raise exception 'Report archive permission required'; end if;
  if new_status in ('open','reviewing','resolved') and not public.has_admin_permission('reports.resolve') then raise exception 'Report resolution permission required'; end if;
  update public.reports set status = new_status where id = target_report_id;
end;
$$;
revoke all on function public.admin_update_report(uuid, text) from public, anon;
grant execute on function public.admin_update_report(uuid, text) to authenticated;

create or replace function public.limit_monthly_streak_protections()
returns trigger language plpgsql set search_path = public as $$
declare configured_limit integer;
begin
  select streak_max_protections into configured_limit from public.platform_settings where singleton = true;
  configured_limit := coalesce(configured_limit, 5);
  if exists (select 1 from public.reading_sessions where user_id = new.user_id and occurred_on = new.protected_on) then
    raise exception 'reading already registered on this day';
  end if;
  if (select count(*) from public.streak_protections where user_id = new.user_id
      and date_trunc('month', protected_on) = date_trunc('month', new.protected_on)) >= configured_limit then
    raise exception 'monthly protection limit reached';
  end if;
  return new;
end;
$$;

drop policy if exists "users create own streak protections" on public.streak_protections;

create or replace function public.apply_automatic_streak_protections()
returns integer language plpgsql security definer set search_path = public as $$
declare last_activity date; target_day date; first_day date; configured_days integer; configured_limit integer; applied integer := 0;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select streak_days_displayed, streak_max_protections into configured_days, configured_limit
  from public.platform_settings where singleton = true;
  configured_days := coalesce(configured_days, 30);
  configured_limit := coalesce(configured_limit, 5);
  select max(activity_day) into last_activity from (
    select max(occurred_on) activity_day from public.reading_sessions where user_id = auth.uid()
    union all
    select max(protected_on) from public.streak_protections where user_id = auth.uid() and protected_on < current_date
  ) activity;
  if last_activity is null then return 0; end if;
  first_day := greatest(last_activity + 1, current_date - configured_days);
  if first_day > current_date - 1 then return 0; end if;
  for target_day in select generate_series(first_day, current_date - 1, interval '1 day')::date loop
    if exists (select 1 from public.reading_sessions where user_id = auth.uid() and occurred_on = target_day) then continue; end if;
    if (select count(*) from public.streak_protections where user_id = auth.uid()
        and date_trunc('month', protected_on) = date_trunc('month', target_day)) >= configured_limit then continue; end if;
    insert into public.streak_protections(user_id, protected_on, status)
    values(auth.uid(), target_day, 'used') on conflict(user_id, protected_on) do nothing;
    if found then applied := applied + 1; end if;
  end loop;
  return applied;
end;
$$;
revoke all on function public.apply_automatic_streak_protections() from public, anon;
grant execute on function public.apply_automatic_streak_protections() to authenticated;
